services:
  server:
    build:
      context: .
      dockerfile: ./src/GoodHamburger.API/Dockerfile
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
    ports:
      - 8080:8080